#!/usr/bin/bash
announce() {
	echo "----------------------------"
	echo "----- [ $1 ] -----"
	echo "----------------------------"
}

announce "CLEANING" && mvn clean &&\
 announce "COMPILING" &&  mvn compile &&\
 announce "RUNNING" && ./run "$*"
